import Link from "next/link";
import { productCopy } from "@/lib/productCopy";

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-4xl px-6 py-12">
      <section className="rounded-2xl border border-gray-200 bg-white p-8 shadow-sm">
        <p className="text-sm font-semibold uppercase tracking-wide text-gray-500">
          Legal
        </p>

        <h1 className="mt-3 text-4xl font-bold tracking-tight text-gray-950">
          Terms of Service
        </h1>

        <p className="mt-4 text-sm leading-6 text-gray-600">
          Last updated: June 18, 2026
        </p>

        <div className="mt-8 space-y-8 text-sm leading-7 text-gray-700">
          <section>
            <h2 className="text-xl font-semibold text-gray-950">
              1. Acceptance of Terms
            </h2>

            <p className="mt-3">
              By accessing or using OrthodoxAI, you agree to these Terms of
              Service. If you do not agree, you should not use the service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-950">
              2. Nature of the Service
            </h2>

            <p className="mt-3">
              OrthodoxAI is an educational software tool designed to help users
              reflect on Orthodox Christian prayer, fasting, Scripture,
              journaling, and spiritual discipline.
            </p>

            <p className="mt-3">
              OrthodoxAI does not replace the Church, a priest, confession,
              pastoral counsel, medical advice, psychological help, or emergency
              services.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-950">
              3. No Clergy, Medical, or Professional Advice
            </h2>

            <p className="mt-3">
              Responses generated by OrthodoxAI are informational and
              educational. They should not be treated as spiritual authority,
              confession, pastoral direction, medical advice, mental health
              advice, legal advice, or emergency assistance.
            </p>

            <p className="mt-3">
              For personal spiritual rules, confession, fasting exceptions,
              serious moral questions, family crises, addiction, abuse, mental
              health concerns, self-harm, or emergencies, you should contact an
              appropriate priest, qualified professional, or emergency service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-950">
              4. User Accounts
            </h2>

            <p className="mt-3">
              You are responsible for maintaining the confidentiality of your
              account credentials and for all activity that occurs under your
              account.
            </p>

            <p className="mt-3">
              You agree to provide accurate information when creating an account
              and to use the service only for lawful purposes.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-950">
              5. Subscriptions and Billing
            </h2>

            <p className="mt-3">
              OrthodoxAI may offer paid subscription features through
              third-party payment providers such as Stripe. Subscription pricing,
              billing intervals, and available features may be shown on the
              pricing page.
            </p>

            <p className="mt-3">
              Subscription management, cancellation, and payment method updates
              may be handled through the billing portal provided by the payment
              processor.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-950">
              6. Acceptable Use
            </h2>

            <p className="mt-3">
              You agree not to misuse OrthodoxAI, attempt to disrupt the
              service, access accounts that do not belong to you, scrape or
              reverse engineer the service, or use it for unlawful, abusive, or
              harmful purposes.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-950">
              7. AI-Generated Content
            </h2>

            <p className="mt-3">
              OrthodoxAI may generate incomplete, inaccurate, or inappropriate
              responses. You are responsible for evaluating the usefulness and
              correctness of any output before relying on it.
            </p>

            <p className="mt-3">
              OrthodoxAI should be used with discernment and should not be
              treated as an authoritative source of Church teaching or personal
              spiritual direction.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-950">
              8. Changes to the Service
            </h2>

            <p className="mt-3">
              We may modify, suspend, or discontinue parts of the service at any
              time. We may also update these Terms from time to time.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-950">
              9. Contact
            </h2>

            <p className="mt-3">
              For questions about these Terms, contact the operator of
              OrthodoxAI.
            </p>
          </section>
        </div>

        <div className="mt-10 rounded-xl border border-gray-200 bg-gray-50 p-5 text-sm leading-6 text-gray-600">
          <p>{productCopy.disclaimer}</p>
        </div>

        <div className="mt-8">
          <Link
            href="/dashboard"
            className="rounded-lg bg-gray-950 px-5 py-3 text-sm font-semibold text-white hover:bg-gray-800"
          >
            Back to Dashboard
          </Link>
        </div>
      </section>
    </main>
  );
}